version: 2
jobs:
  build:
    docker:
      - image: srcml/ubuntu_x86_64_base

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Compile Video Store
          command: cd src && make all
      - run:
          name: Run Video Store
          command: cd src && make run
      - run:
          name: Run Tests in Video Store
          command: cd src && make test