version: 2
jobs:
  build:
    docker:
      - image: srcml/ubuntu_x86_64_base

    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date